<?php

define('TOPTIX_HOST', 'tickets.jer-cin.org.il');
//define('TOPTIX_HOST', '199.203.164.53');

function cinematic_toptix_menu() {
  $items = array();
  $items['admin/content/toptix'] = array(
    'title' => 'toptix',
    'access arguments' => array('administer nodes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cinematic_toptix_import'),
    'file' => 'cinematic_toptix.import.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['content/events-browser'] = array(
    'title' => 'toptix',
    'access arguments' => array('administer nodes'),
    'page callback' => 'cinematic_toptix_browse',
    'file' => 'cinematic_toptix.browse.inc',
  );
  return $items;
}

function cinematic_toptix_cron() {
  $last_time = variable_get('toptix_import', '');
  $this_time = new DateTime();
  $run = FALSE;
  if ($last_time) {
    $last_time = new DateTime($last_time);
    $week = new DateInterval('P1W');
    $run = ($last_time->add($week) <= $this_time);
  }
  else {
    $run = TRUE;
  }
  if ($run) {
    $hour = $this_time->format('G');
    if ($hour >= 23 or $hour <= 6) {
      $message = TopTixImport::import();
      watchdog('toptix import', $message);
      variable_set('toptix_import', $this_time->format('c'));
    }
  }
}

function cinematic_toptix_theme() {
  $themes = array();
  $themes['cinematic_browser'] = array(
    'variables' => array('filters' => array(), 'shows' => array()),
    'template' => 'cinematic-browser',
  );
  return $themes;
}

function cinematic_toptix_block_info() {
  $blocks = array();
  $blocks['cart'] = array(
    'info' => 'toptix basket',
  );
  return $blocks;
}

function cinematic_toptix_block_view($delta) {
  if ($delta != 'cart') {
    return;
  }

  $block = array('title' => '');

  global $language;
  $langadd =  ($language->language == 'en') ? '?culture=en-US' : '';
  
  $output = '<button class="toptix-basket" data-url="http://' . TOPTIX_HOST . '/Order.aspx' . $langadd . '"> ' . t('My cart') . '</button>';
  $esro_frame = '<esro:frame href="http://' . TOPTIX_HOST . '/integrationsample/info.htm" ';
  $esro_frame .= 'width="1024" height="768"/>';
  $output .= '<div id="toptix-frame-wrapper" style="display:none;">' . $esro_frame . '</div>';
  $block['content'] = array(
    '#markup' => $output,
    '#attached' => array(),
  );

  $block['content']['#attached']['library'] = array(
    array('system', 'ui.dialog'),
    array('system', 'jquery.cookie'),
  );

  $path = drupal_get_path('module', 'cinematic_toptix');
  $block['content']['#attached']['js'] = array(
    'http://' . TOPTIX_HOST . '/iframe/esrojsapi.js' => array('group' => JS_LIBRARY, 'type' => 'external'),
    //$path . '/esrojsapi.js' => array('group' => JS_LIBRARY),
    $path . '/basket.js',
  );

  return $block;
}

function cinematic_toptix_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    $form['#submit'][] = 'cinematic_toptix_user_submit';
  }
}

function cinematic_toptix_user_submit($form, &$form_state) {
  $form_state['redirect'] = 'user/' . $form_state['user']->uid;
}

function cinematic_toptix_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['instance']['field_name'] == 'field_toptix_purchase') {
    $element['value']['#type'] = 'hidden';
    $element['browser'] = array(
      '#attributes' => array('class' => array('browser'), 'title' => ''),
      '#type' => 'textfield',
      '#title' => t('Event purchase'),
      '#description' => t('Click to open browser'),
      '#size' => 16,
      '#attached' => array(
        'library' => array(
          array('system', 'ui.accordion'),
          array('system', 'ui.dialog'),
          array('system', 'ui.datepicker'),
        ),
        'js' => array(
          drupal_get_path('module', 'cinematic_toptix') . '/event_browser.js',
        ),
        'css' => array(
          drupal_get_path('module', 'cinematic_toptix') . '/event_browser.css',
        ),
      ),
    );
    if ($element['value']['#default_value']) {
      $event_id = $element['value']['#default_value'];
      $event = db_select('toptix_events', 'te')
        ->condition('te.local_id', $event_id)
        ->fields('te')
        ->execute()->fetchObject();
      if ($event) {
        $element['browser']['#default_value'] = "$event->event_date : $event->local_id";
      }
    }
  }
}

function cinematic_toptix_field_formatter_info() {
  return array(
    'toptix_purchase' => array(
      'label' => 'Toptix Purchase button',
      'field types' => array('number_integer'),
    ),
  );
}

function cinematic_toptix_rdf_namespaces() {
  return array(
    'esro' => 'toptix.com',
  );
}


function cinematic_toptix_field_formatter_view(
  $entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  if ($display['type'] != 'toptix_purchase') {
    return $element;
  }

  $sale_period = field_get_items($entity_type, $entity, 'field_cm_sale_time');
  $sold_out = field_get_items($entity_type, $entity, 'field_tickets_sold_out');
  $sale_open = field_get_items($entity_type, $entity, 'field_include_ticket_sale');

  global $language;
  $langadd = ($language->language == 'en') ? '%26culture=en-US' : '';
  
  foreach ($items as $delta => $item) {
    $disabled = cinematic_toptix_active_sale($sale_period, $sold_out, $sale_open);
    if ($disabled) {
      $output = '<button class="toptix-purchase" disabled title="' . $disabled . '">';
      $output .= t('Tickets') . '</button>';
      $element[$delta] = array(
        '#markup' => $output,
      );
      continue;
    }
    $event_id = $item['value'];
    $url = 'http://' . TOPTIX_HOST . '/loader.aspx/?target=hall.aspx?event=' . $event_id . $langadd;
    $output = '<button class="toptix-purchase" data-url="' . $url . '">' . t('Tickets') . '</button>';
    $element[$delta] = array(
      '#markup' => $output,
      '#attached' => array(
        'js' => array(
          'http://' . TOPTIX_HOST . '/iframe/esrojsapi.js' => array('group' => JS_LIBRARY, 'type' => 'external'),
          //drupal_get_path('module', 'cinematic_toptix') . '/esrojsapi.js' => array('group' => JS_LIBRARY),
          drupal_get_path('module', 'cinematic_toptix') . '/frame.js',
        ),
        'library' => array(
          array('system', 'ui.dialog'),
        ),
      ),
    );
  }

  return $element;
}

function cinematic_toptix_active_sale($sale_period, $sold_out, $sale_open) {
  $disabled = '';
  if ($sale_period) {
    $time_zone = new DateTimeZone($sale_period[0]['timezone']);
    $now = new DateTime('now', $time_zone);
    $date_check = new DateTime('now', $time_zone);
    $date_check->setTimestamp($sale_period[0]['value']);
    if ($now < $date_check) {
      $date_text = $date_check->format('d M Y');
      $disabled = t('Sale opens at @date', array('@date' => $date_text));
    }
    else {
      $date_check->setTimestamp($sale_period[0]['value2']);
      if ($now > $date_check) {
        $date_text = $date_check->format('d M Y');
        $disabled = t('Sale has ended at @date', array('@date' => $date_text));
      }
    }
  }
  if ($sold_out and $sold_out[0]['value']) {
    $disabled = t('Sold out');
  }
  if ($sale_open and !($sale_open[0]['value'])) {
    $disabled = t('Sale closed');
  }
  return $disabled;
}
