<?php

/**
 * Implements hook_init().
 */

function da11y_init() {
	drupal_add_css(drupal_get_path('module', 'da11y') . '/assets/css/style.css');
	drupal_add_js(drupal_get_path('module', 'da11y') . '/assets/js/app.dev.js');
	
	$settings=array();
	foreach (variable_get('da11y_setting','') as $key=>$value) {
		
		$settings[$key]=(strpos($key,'da11y_')===false)?$value:t($value);
	}
	
	drupal_add_js(array(
		'da11y_setting' =>$settings
	), 'setting');
}


/**
 * Implements hook_menu().
 */

function da11y_menu() {
  $items['admin/config/da11y'] = array(
    'title' => 'Da11y Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('da11y_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'da11y_settings.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}



