<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function node_teaser_menu(){
	$items['node/title/autocomplete'] = array(
        'page callback' => 'fetch_node_titles',
        'access arguments' => array('access test autocomplete'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function node_teaser_ctools_plugin_directory($module, $plugin) {
    if ($module == 'ctools' && $plugin == 'content_types') {
       return 'plugins/' . $plugin;
     }
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_page_build()
 */
function node_teaser_page_build(&$page) {
  // Add our custom css to the footer to override other things.
   drupal_add_css(drupal_get_path('module', 'node_teaser') . '/node_teaser.css');
}

/**
 * Implementation of hook_form_alter()
 */
function node_teaser_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'node_teaser_node_content_form'){
        drupal_add_js(drupal_get_path('module', 'node_teaser') . '/node_teaser.js');
    }
}
/**
 * node nid and title as option based on content type
 */


function fetch_node_titles($string) {
	if (isset($_POST['content_type'])) {
		$content_type = $_POST['content_type'];
		variable_set('content_type', $_POST['content_type']);
	}
	elseif (variable_get('content_type') != NULL) {
		$content_type = variable_get('content_type');
	}
	else {
		$content_type = "cm_article";
		variable_set('content_type', 'cm_article');
	}
	if (isset($_POST['str'])) {
		$search_string = $_POST['str'];
	} else {
		$search_string = $string;
	}
    $output = array();
    $result = db_query("SELECT nid,title,type from node where type = '$content_type' AND title LIKE '%$search_string%'")->fetchAll();
    foreach ($result as $val) {
        $nid = $val->title . '(' . $val->nid . ')';
        $output[$nid ] = check_plain($val->title . ' (' . $val->nid . ')');
    }
    drupal_json_output($output);
}