<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function node_teaser_menu(){
    $items['ajax/content-type/node'] = array(
        'title' => '',
        'page callback' => 'node_type_content',
        'access callback' => true
    );
    return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function node_teaser_ctools_plugin_directory($module, $plugin) {
    if ($module == 'ctools' && $plugin == 'content_types') {
       return 'plugins/' . $plugin;
     }
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_page_build()
 */
function node_teaser_page_build(&$page) {
  // Add our custom css to the footer to override other things.
   drupal_add_css(drupal_get_path('module', 'node_teaser') . '/node_teaser.css');
}

/**
 * Implementation of hook_form_alter()
 */
function node_teaser_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'node_teaser_node_content_form'){
        drupal_add_js(drupal_get_path('module', 'node_teaser') . '/node_teaser.js');
    }
}
/**
 * node nid and title as option based on content type
 */
function node_type_content() {
   $type = isset($_POST['content_type']) ? $_POST['content_type'] : '';
   $default_nid = isset($_POST['default_nid']) ? $_POST['default_nid'] : '';
    $result = db_query("SELECT nid,title from node where type = '$type'")->fetchAll();
    foreach ($result as $val) {
        $selected = '';
        if($default_nid == $val->nid){
            $selected = "selected=selected";
        }
        $output.="<option value='$val->nid' $selected>$val->title</option>";
    }
    drupal_json_output(array('output' =>$output));
    die();

}