<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function node_teaser_menu(){
    $items['node/autocomplete'] = array(
        'title' => '',
        'page callback' => 'node_type_content',
        'access arguments' => array('access test autocomplete'),
        'type' => MENU_CALLBACK,
        'access callback' => true
    );
    return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function node_teaser_ctools_plugin_directory($module, $plugin) {
    if ($module == 'ctools' && $plugin == 'content_types') {
       return 'plugins/' . $plugin;
     }
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_page_build()
 */
function node_teaser_page_build(&$page) {
  // Add our custom css to the footer to override other things.
   drupal_add_css(drupal_get_path('module', 'node_teaser') . '/node_teaser.css');
}

/**
 * Implementation of hook_form_alter()
 */
function node_teaser_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'node_teaser_node_content_form'){
        drupal_add_js(drupal_get_path('module', 'node_teaser') . '/node_teaser.js');
    }
}
/**
 * node nid and title as option based on content type
 */
//function node_type_content() {
//   $type = isset($_POST['content_type']) ? $_POST['content_type'] : '';
//   $default_nid = isset($_POST['default_nid']) ? $_POST['default_nid'] : '';
//    $result = db_query("SELECT nid,title from node where type = '$type'")->fetchAll();
//    foreach ($result as $val) {
//        $selected = '';
//        if($default_nid == $val->nid){
//            $selected = "selected=selected";
//        }
//        $output.="<option value='$val->nid' $selected>$val->title</option>";
//    }
//    drupal_json_output(array('output' =>$output));
//    die();
//
//}

function node_type_content() {
   $type = isset($_POST['content_type']) ? $_POST['content_type'] : '';
   //$default_nid = isset($_POST['default_nid']) ? $_POST['default_nid'] : '';
   drupal_set_message('<pre>'.print_r($type, 1).'</pre>');
    $output = array();
    $result = db_query("SELECT nid,title,type from node where type = '$type'")->fetchAll();
    foreach ($result as $val) {
        
        //drupal_set_message('<pre>'.print_r($val, 1).'</pre>');
        $output[$val->nid] = check_plain($val->title);
    }
    drupal_json_output($output);
    die();

}