<?php
function view_navigation_views_post_execute(&$view) {
	
switch ($view->name) {
    case 'festival_calendar':
	if ($view->current_display !='page') return;
	$result_array=array();
	foreach ($view->result as $key=>$result_item){
		if(!empty($result_item->nid))$result_array[]=$result_item->nid;
	}
	if (!empty($result_array))$_SESSION['link_node']=$result_array;
	break;
	case 'lobby':
	if ($view->current_display !='panel_pane_1') return;
	$result_array=array();
	foreach ($view->result as $key=>$result_item){
		if(!empty($result_item->node_taxonomy_index_nid))$result_array[]=$result_item->node_taxonomy_index_nid;
	}
	if (!empty($result_array))$_SESSION['link_node']=$result_array;
	break;
}
}

function _get_node_next_link() {
	if (empty($_SESSION['link_node'])) return;
	$nid='';
	$output='';
	$prev=$_SERVER['HTTP_REFERER'];
	$link_array=$_SESSION['link_node'];
	if ($node = menu_get_object()) {
	$nid = $node->nid;
	}
	if (strpos($prev, 'festival-calendar')!==FALSE||
		strpos($prev, 'article/4284')!==FALSE||
		strpos($prev, 'article/4285')!==FALSE||
		strpos($prev, 'lobby/')!==FALSE
	) {
		$_SESSION['link_prev']=$nid;
	} elseif (!empty($_SESSION['link_prev']) && strpos($prev, $_SESSION['link_prev'])===FALSE){
		//unset($_SESSION['link_node']);
		return;
	}
	if (empty($_SESSION['link_prev']) || !in_array($_SESSION['link_prev'], $link_array)) return;
	$key = array_search ($nid, $link_array);
	if ($key===FALSE){
		//unset($_SESSION['link_node']);
		return;
	}
	$next_nid=$link_array[$key+1];
	$prev_nid=$link_array[$key-1];
	$output.=(!empty($next_nid))?'<div class="button-next"><a class="button-next" href="'.url('node/'.$next_nid).'">'.t('Next').'</a>
	<a class="button-next-title" href="'.url('node/'.$next_nid).'">'.node_load($next_nid)->title.'</a></div>':'';
	$output.=(!empty($prev_nid))?'<div class="button-prev"><a class="button-prev" href="'.url('node/'.$prev_nid).'">'.t('Previous').'</a>
	<a class="button-prev-title" href="'.url('node/'.$next_nid).'">'.node_load($prev_nid)->title.'</a></div>':'';
	$_SESSION['link_prev']=$nid;
	return $output;
}

function view_navigation_block_info() {    
  $blocks['next_button_block'] = array(
    // info: The name of the block.
    'info' => t('Next Previous Button Block'),
  );

  return $blocks;
}

function view_navigation_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'next_button_block':
	$block['content']=_get_node_next_link();
	break;
   }

  return $block;
}