<?php

function cinematic_festival_field_widget_form_alter(&$element, &$form_state, $context) {
  $instance = $context['instance'];
  if (
    $instance['entity_type'] != 'taxonomy_term' or
    $instance['bundle'] != 'festival'
  ) {
    return;
  }

  if ($instance['field_name'] == 'field_cm_domain') {
    $element['value']['#type'] = 'select';
    $options = array();
    foreach (domain_domains() as $domain_id => $domain) {
      $options[$domain_id] = check_plain($domain['sitename']);
    }
    $element['value']['#options'] = $options;
    unset($element['value']['#size']);
  }

}

function cinematic_festival_taxonomy_term_load($terms) {
  $query = db_select('cinematic_term_menu', 'tm');
  $query->condition('tid', array_keys($terms), 'IN');
  $query->fields('tm', array('tid', 'menu_name'));
  $records = $query->execute()->fetchAllKeyed();
  foreach ($terms as $tid => &$term) {
    if (isset($records[$tid])) {
      $term->cinematic_menu = $records[$tid];
    }
    else {
      $term->cinematic_menu = NULL;
    }
  }
}

function cinematic_festival_taxonomy_term_view($term, $view_mode, $langcode) {
  if (empty($term->cinematic_menu)) {
    return;
  }
  $menu = menu_load($term->cinematic_menu);
  $edit = l($menu['title'], 'admin/structure/menu/manage/' . $menu['menu_name']);
  $term->content['cinematic_menu'] = array('#markup' => $edit);
}

function cinematic_festival_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
  if ($form_state['term']->vocabulary_machine_name != 'festival') {
    return;
  }

  if (empty($form_state['term']->cinematic_menu)) {
    $form_state['term']->cinematic_menu = NULL;
  }

  $term = $form_state['term'];

  $form['cinematic_menu'] = array( 
    '#type' => 'select',
    '#title' => t('Menu'),
  );
  $options = array();
  foreach (menu_get_menus() as $menu_name => $menu_title) {
    $options[$menu_name] = $menu_title;
  }
  if (empty($term->cinematic_menu) or !isset($options[$term->cinematic_menu])) {
    $options = array('new' => t('Dedicated')) + $options;
  }
  else {
    $form['cinematic_menu']['#default_value'] = $term->cinematic_menu;
  }
  $form['cinematic_menu']['#options'] = $options;
}

function cinematic_festival_taxonomy_term_insert($term) {
  cinematic_festival_taxonomy_term_update($term);
}

function cinematic_festival_taxonomy_term_update($term) {
  if($term->vocabulary_machine_name != 'festival') {return;}
  if ($term->cinematic_menu == 'new') {
    $menu = array(
      'menu_name' => 'cinematic-festival-' . $term->tid,
      'title' => t('Dedicated menu for: ' . $term->name),
      'description' => t('festival dedicated menu'),
    );
    menu_save($menu);
    $term->cinematic_menu = $menu['menu_name'];
  }

  db_merge('cinematic_term_menu')
    ->key(array('tid' => $term->tid))
    ->fields(array(
      'menu_name' => $term->cinematic_menu,
    ))
    ->execute();
}

function cinematic_festival_taxonomy_term_delete($term) {
  if ($term->vocabulary_machine_name != 'festival') {
    return;
  }
  db_delete('cinematic_term_menu')
    ->condition('tid', $term->tid)
    ->execute();
}
