<?php


function cm_toptix_user_insert(&$edit, $account, $category) {
    drupal_goto('/ty/'.$account->uid);
    //echo "<script type='text/javascript'>console.log('".$account->uid."')</script>";
    /*
    //$edit['field_toptix_id']['und'][0] = '2222';
    drupal_set_message($account->mail);
    drupal_set_message(drupal_get_path('module', 'cm_toptix'));
    //drupal_add_js(drupal_get_path('module', 'cm_toptix') . '/js/basics.js');
    //drupal_add_js('http://localhost/public_html/sites/all/modules/cm_toptix'. '/js/basics.js');


    db_insert('field_data_field_toptix_id')
        ->fields(array(
            'field_toptix_id_value' => '1111',
            'entity_id' => $account->uid,
            'revision_id' => $account->uid,
            'entity_type' => 'user',
            'bundle' => 'user',
            'deleted' => 0,
            'delta' => 0,
            'language' => 'und',
        ))
        ->execute();
*/
}


function cm_toptix_menu() {
    $items['ty'] = array(
        'title' => t('Thank you page'),
        'description' => t("Thank you page"),
        'page callback' => 'cm_toptix_ty',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

function cm_toptix_ty($uid = 0) {
    global $user;
    $html = "<h1>Your account has been created.</h1><p>Thank you for registering with Cinematheque. Your account has been created, and a verification email has been sent to your registered email address. Please click on the verification link included in the email to activate your account.</p><h2>Important! Your account will not be activated until you verify your email address.</h2>";
    $html .= "<script type='text/javascript'>console.log('".$uid."')</script>";

    return $html;
}
?>